// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type House struct {
	ID          int      `json:"id"`
	RealtorName string   `json:"realtorName"`
	Address     string   `json:"address"`
	Issues      []*Issue `json:"issues"`
}

type HouseInput struct {
	RealtorName string        `json:"realtorName"`
	Address     string        `json:"address"`
	Issues      []*IssueInput `json:"issues"`
}

type Issue struct {
	ID               int    `json:"id"`
	IssueTitle       string `json:"issueTitle"`
	IssueDescription string `json:"issueDescription"`
	Urgent           bool   `json:"urgent"`
}

type IssueInput struct {
	IssueTitle       string `json:"issueTitle"`
	IssueDescription string `json:"issueDescription"`
	Urgent           bool   `json:"urgent"`
}
